language: java
sudo: false
before_install:
  - "echo \"export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g -XX:MaxPermSize=2048m'\" > ~/.mavenrc"
jdk:
  - oraclejdk7
cache:
  directories:
  - $HOME/.m2
script: mvn help:system
